# 请严格按照以下顺序编写配置, 并且所有环境必须配置
# key:
#   # 注释: 如 host 等
#   owner:
#   description:
#   db_type: [mssql|mysql]
#   dev:
#     user:
#     passwd:
#     host:
#     port:
#     db:  # mysql 必填
#   uat:
#   pre:
#   prod:

database_mysql_cps:
  owner: ~
  description: ~
  db_type: mysql
  dev:
    user: root
    passwd: root
    host: 192.168.1.100
    port: 3406
    db: fund_wap
  uat:
    user: root
    passwd: root
    host: 192.168.1.100
    port: 3402
    db: fund_wap
  pre:
    user: root
    passwd: root
    host: 192.168.1.100
    port: 3406
    db: fund_wap
  prod:
    user: root
    passwd: root
    host: 192.168.1.100
    port: 3406
    db: fund_wap
