# 请严格按照以下顺序编写配置, 并且所有环境必须配置
# key:
#   # 注释: 如 host 等
#   owner:
#   description:
#   db_type: [mssql|mysql]
#   dev:
#     user:
#     passwd:
#     host:
#     port:
#     db:  # mysql 必填
#   uat:
#   pre:
#   prod:

db_fund_wap_mysql:
  owner: ~
  description: ~
  db_type: mysql
  dev:
    user: tangdou
    passwd: Aa.654321
    host: 127.0.0.1
    port: 3306
    db: fund_wap
  pre:
    user: tangdou
    passwd: Aa.654321
    host: 127.0.0.1
    port: 3306
    db: fund_wap
  prod:
    user: tangdou
    passwd: Aa.654321
    host: 127.0.0.1
    port: 3306
    db: fund_wap
